### ISSUE TITLE
'adata = sm.tl.spatial_distance' runs into ValueError: need at most x handles....

### ISSUE THREAD

**Issue by josenimo** [labsyspharm/scimap#44]
Dear Scimap developer,

I am looking forward to analyzing my images with your package, so far every step of the way has worked but now the spatial distance is running into an ValueError

the command:
```
adata = sm.tl.spatial_distance (adata, 
                               x_coordinate='X_centroid', y_coordinate='Y_centroid', 
                               z_coordinate=None, 
                               phenotype='phenotype', 
                               subset=None, 
                               imageid='imageid', 
                               label='spatial_distance')
```

the stack trace:
```
Exception in thread ExecutorManagerThread:
Traceback (most recent call last):
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\scimap\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\scimap\lib\site-packages\joblib\externals\loky\process_executor.py", line 557, in run
    result_item, is_broken, bpe = self.wait_result_broken_or_wakeup()
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\scimap\lib\site-packages\joblib\externals\loky\process_executor.py", line 611, in wait_result_broken_or_wakeup
    ready = wait(readers + worker_sentinels)
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\scimap\lib\multiprocessing\connection.py", line 879, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\scimap\lib\multiprocessing\connection.py", line 811, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 129
```

<details> 
<summary> conda list</summary>

```

# packages in environment at C:\Users\Administrator\Jose_BI\Anaconda\envs\scimap:
#
# Name                    Version                   Build  Channel
aiobotocore               2.4.0                    pypi_0    pypi
aiofiles                  22.1.0                   pypi_0    pypi
aiohttp                   3.8.3                    pypi_0    pypi
aioitertools              0.11.0                   pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
aiosqlite                 0.18.0                   pypi_0    pypi
alabaster                 0.7.12                   pypi_0    pypi
anndata                   0.7.8                    pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
asttokens                 2.0.8                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
atomicwrites              1.4.1                    pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
babel                     2.10.3                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
bleach                    5.0.1                    pypi_0    pypi
botocore                  1.27.59                  pypi_0    pypi
build                     0.8.0                    pypi_0    pypi
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.9.24            h5b45459_0    conda-forge
cachey                    0.2.1                    pypi_0    pypi
certifi                   2022.9.24                pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.5                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
contourpy                 1.0.5                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.28                  pypi_0    pypi
dask                      2.30.0                   pypi_0    pypi
debugpy                   1.6.3                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
docstring-parser          0.15                     pypi_0    pypi
docutils                  0.19                     pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 1.1.0                    pypi_0    pypi
fasteners                 0.18                     pypi_0    pypi
fastjsonschema            2.16.2                   pypi_0    pypi
fonttools                 4.37.4                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
freetype-py               2.3.0                    pypi_0    pypi
frozenlist                1.3.1                    pypi_0    pypi
fsspec                    2022.8.2                 pypi_0    pypi
gensim                    4.2.0                    pypi_0    pypi
ghp-import                2.1.0                    pypi_0    pypi
h5py                      3.7.0                    pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
hsluv                     5.0.3                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
igraph                    0.10.1                   pypi_0    pypi
imageio                   2.22.1                   pypi_0    pypi
imageio-ffmpeg            0.4.8                    pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        5.0.0                    pypi_0    pypi
importlib-resources       5.9.0                    pypi_0    pypi
ipykernel                 6.16.0                   pypi_0    pypi
ipython                   8.5.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.2                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
json5                     0.9.11                   pypi_0    pypi
jsonpointer               2.3                      pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            8.0.2                    pypi_0    pypi
jupyter-console           6.4.4                    pypi_0    pypi
jupyter-core              5.2.0                    pypi_0    pypi
jupyter-events            0.5.0                    pypi_0    pypi
jupyter-server            2.2.1                    pypi_0    pypi
jupyter-server-fileid     0.6.0                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyter-server-ydoc       0.6.1                    pypi_0    pypi
jupyter-ydoc              0.2.2                    pypi_0    pypi
jupyterlab                3.6.1                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.19.0                   pypi_0    pypi
jupyterlab-widgets        3.0.3                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
leidenalg                 0.9.0                    pypi_0    pypi
libffi                    3.4.2                h8ffe710_5    conda-forge
libsqlite                 3.39.4               hcfcfb64_0    conda-forge
libzlib                   1.2.12               hcfcfb64_4    conda-forge
llvmlite                  0.38.1                   pypi_0    pypi
magicgui                  0.5.1                    pypi_0    pypi
markdown                  3.3.7                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.6.0                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mergedeep                 1.3.4                    pypi_0    pypi
mistune                   2.0.4                    pypi_0    pypi
mkdocs                    1.4.0                    pypi_0    pypi
mkdocs-material           7.3.6                    pypi_0    pypi
mkdocs-material-extensions 1.0.3                    pypi_0    pypi
more-itertools            8.14.0                   pypi_0    pypi
multidict                 6.0.2                    pypi_0    pypi
napari                    0.4.16                   pypi_0    pypi
napari-brightness-contrast 0.1.8                    pypi_0    pypi
napari-console            0.0.6                    pypi_0    pypi
napari-ome-zarr           0.4.0                    pypi_0    pypi
napari-plugin-engine      0.2.0                    pypi_0    pypi
napari-svg                0.1.6                    pypi_0    pypi
napari-tools-menu         0.1.19                   pypi_0    pypi
natsort                   8.2.0                    pypi_0    pypi
nbclassic                 0.5.1                    pypi_0    pypi
nbclient                  0.7.0                    pypi_0    pypi
nbconvert                 7.2.1                    pypi_0    pypi
nbformat                  5.7.0                    pypi_0    pypi
nest-asyncio              1.5.6                    pypi_0    pypi
networkx                  2.8.7                    pypi_0    pypi
notebook                  6.4.12                   pypi_0    pypi
notebook-shim             0.2.2                    pypi_0    pypi
npe2                      0.6.1                    pypi_0    pypi
numba                     0.55.2                   pypi_0    pypi
numcodecs                 0.10.2                   pypi_0    pypi
numpy                     1.22.4                   pypi_0    pypi
numpydoc                  1.4.0                    pypi_0    pypi
ome-zarr                  0.6.0                    pypi_0    pypi
openssl                   3.0.5                hcfcfb64_2    conda-forge
packaging                 21.3                     pypi_0    pypi
pandas                    1.5.0                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
patsy                     0.5.2                    pypi_0    pypi
pep517                    0.13.0                   pypi_0    pypi
phenograph                1.5.7                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.2.0                    pypi_0    pypi
pint                      0.19.2                   pypi_0    pypi
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              2.6.2                    pypi_0    pypi
plotly                    4.14.3                   pypi_0    pypi
pluggy                    0.13.1                   pypi_0    pypi
prometheus-client         0.14.1                   pypi_0    pypi
prompt-toolkit            3.0.31                   pypi_0    pypi
psutil                    5.9.2                    pypi_0    pypi
psygnal                   0.4.2                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pydantic                  1.10.2                   pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pymdown-extensions        9.6                      pypi_0    pypi
pynndescent               0.5.7                    pypi_0    pypi
pyopengl                  3.1.6                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyqt5                     5.15.9                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.11.1                  pypi_0    pypi
pyqtgraph                 0.13.1                   pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
pytest                    5.4.3                    pypi_0    pypi
pytest-xvfb               2.0.0                    pypi_0    pypi
python                    3.8.13          hcf16a7b_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-json-logger        2.0.4                    pypi_0    pypi
pytomlpp                  1.0.11                   pypi_0    pypi
pytz                      2022.4                   pypi_0    pypi
pyvirtualdisplay          3.0                      pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pywin32                   304                      pypi_0    pypi
pywinpty                  2.0.8                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyyaml-env-tag            0.1                      pypi_0    pypi
pyzmq                     24.0.1                   pypi_0    pypi
qtconsole                 5.3.2                    pypi_0    pypi
qtpy                      2.2.1                    pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
retrying                  1.3.3                    pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rich                      12.6.0                   pypi_0    pypi
s3fs                      2022.8.2                 pypi_0    pypi
scanpy                    1.9.1                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.1.2                    pypi_0    pypi
scimap                    0.22.9                   pypi_0    pypi
scipy                     1.9.1                    pypi_0    pypi
seaborn                   0.11.2                   pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
session-info              1.0.0                    pypi_0    pypi
setuptools                65.4.1             pyhd8ed1ab_0    conda-forge
shapely                   1.8.4                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sklearn                   0.0                      pypi_0    pypi
smart-open                6.2.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sphinx                    5.2.3                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.39.4               hcfcfb64_0    conda-forge
stack-data                0.5.1                    pypi_0    pypi
statsmodels               0.13.2                   pypi_0    pypi
stdlib-list               0.8.0                    pypi_0    pypi
superqt                   0.3.5                    pypi_0    pypi
terminado                 0.16.0                   pypi_0    pypi
texttable                 1.6.4                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2020.12.8                pypi_0    pypi
tinycss2                  1.1.1                    pypi_0    pypi
tk                        8.6.12               h8ffe710_0    conda-forge
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
typer                     0.6.1                    pypi_0    pypi
typing-extensions         4.3.0                    pypi_0    pypi
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
umap-learn                0.5.3                    pypi_0    pypi
uri-template              1.2.0                    pypi_0    pypi
urllib3                   1.26.12                  pypi_0    pypi
vc                        14.2                 hac3ee0b_8    conda-forge
vispy                     0.10.0                   pypi_0    pypi
vs2015_runtime            14.29.30139          h890b9b1_8    conda-forge
watchdog                  2.1.9                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webcolors                 1.12                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.5.1                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.3                    pypi_0    pypi
wrapt                     1.14.1                   pypi_0    pypi
xlrd                      1.2.0                    pypi_0    pypi
xz                        5.2.6                h8d14728_0    conda-forge
y-py                      0.5.5                    pypi_0    pypi
yarl                      1.8.1                    pypi_0    pypi
ypy-websocket             0.8.2                    pypi_0    pypi
zarr                      2.10.3                   pypi_0    pypi
zipp                      3.8.1                    pypi_0    pypi

```

</details>

https://filetransfer.mdc-berlin.de/scimap_spatial_bug/
I am uploading my raw data, the adata object, the phenotyping table, and the gates. as well as the entire jupyter notebook. Thank you for your help!

Edit:
I was able to run it in my laptop, but not my workstation.. something about windows is messing it up.
I will update if I figure it out

**Comment by ajitjohnson** [comment]
Dear @josenimo I think it is the parallelization function that is giving you trouble. I am not able to download your data btw. Requires a username and password.

**Comment by josenimo** [comment]
Dear @ajitjohnson, thank you, do you have any idea where I could look for help about this windows issue? Since I was able to run it in my laptop, I think this problem is just for my workstation setup.

Thank you for scimap, it is a great tool!

Here are the files:
https://filetransfer.mdc-berlin.de/?u=HqR4M6kQ&p=PnKfYP7Y
Username: HqR4M6kQ
Password: PnKfYP7Y
